### ISSUE TITLE
How to stream audio from client to server?

### ISSUE THREAD

**Issue by sainimohit23** [miguelgrinberg/socketio-examples#4]
Hi, I am working on a project where I need to stream audio from the user's browser to the remote flask server. On the server, there will be a deep learning model that will return the predictions in real-time. Now, I am really struggling to find a way to stream audio from the user's machine to the server.

I was able to do this locally (without flask) using pyaudio. But, now I am working on a Flask API to achieve the same goal.

**Comment by sainimohit23** [comment]
I misunderstood the description. After installing the requirements in my anaconda environment. I am getting this error-

```
Traceback (most recent call last):
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3023, in _dep_map
    return self.__dep_map
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2817, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3014, in _parsed_pkg_info
    return self._pkg_info
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2817, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/v-mohit.saini/anaconda3/envs/flask/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/flask/cli.py", line 336, in get_command
    self._load_plugin_commands()
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/flask/cli.py", line 332, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 795, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2738, in requires
    dm = self._dep_map
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3025, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3034, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3016, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1421, in get_metadata
    value = self._get(path)
  File "/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1617, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/v-mohit.saini/anaconda3/envs/flask/lib/python3.6/site-packages/MarkupSafe-1.1.1.dist-info/METADATA'
```

**Comment by sainimohit23** [comment]
Found the problem. Installing the new libraries in previous environment messed it up(I have to set it up again :'( ). Creating new environment is worked. Closing.
